package:
  name: numactl-libs-cos7-ppc64le
  version: 2.0.12

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/numactl-libs-2.0.12-3.el7.ppc64le.rpm
    sha256: ca85f87067c8a12763658b525ac584585f8d5bf692b97d98451a3a39c4942c17
    folder: binary

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'

test:
  commands:
    - test -d "${PREFIX}/powerpc64le-conda_cos7-linux-gnu/sysroot"
  requires:
    - zlib

about:
  home: ftp://oss.sgi.com/www/projects/libnuma/download
  license: LGPLv2/GPLv2
  license_family: GPL2
  license_file:
    - copyright.txt
    - gpl-2.0.txt
    - lgpl-2.1.txt
  summary: "(CDT) Library for tuning for Non Uniform Memory Access machines"
  description: |
        Simple NUMA policy support. It consists of a numactl program to run other
        programs with a specific NUMA policy and a libnuma to do allocations with NUMA
        policy in applications.

extra:
  recipe-maintainers:
    - jakirkham
    - ychfan
